### ISSUE TITLE
[I] Remove Bnyro from app contributors

### ISSUE THREAD

**Issue by therealbluepandabear** [therealbluepandabear/PixaPencil#158]
Figure out how to remove @Bnyro from app contributors.

**Comment by Bnyro** [comment]
You have meme potential

**Comment by Bnyro** [comment]
Tbh I don't really understand your problem, I just have other stuff to do than answering your questions 24/7.
And I think you should really overthink your political position cause your current mindset won't help you in the real world.

All the best

Bnyro

**Comment by therealbluepandabear** [comment]
Unfortunately this is not possible without breaking the codebase, so I will have to deal with the fact that I have some a tiny brown stain on my codebase. Oh well.
