### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [therealbluepandabear/PixaPencil#171]
**Describe the bug**

```
> Task :app:kaptReleaseKotlin
/home/vagrant/build/com.therealbluepandabear.pixapencil/app/build/tmp/kapt3/stubs/release/com/therealbluepandabear/pixapencil/database/PixelArtDatabase.java:7: error: Schema '3.json' required for migration was not found at the schema out folder: /home/vagrant/build/com.therealbluepandabear.pixapencil/app/schemas/com.therealbluepandabear.pixapencil.database.PixelArtDatabase. Cannot generate auto migrations.
public abstract class PixelArtDatabase extends androidx.room.RoomDatabase {
                ^

> Task :app:kaptReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

```

Could you please take a look? Thanks!

**Comment by therealbluepandabear** [comment]
I am confused as to why F-Droid is getting this error -- I encountered this earlier while developing the app, and I thought to have fixed it.

 I have had no errors generating a **signed apk** for 0.1.7-beta1, as well as **upgrading** from 0.1.6 to 0.1.7-beta1.

**Comment by therealbluepandabear** [comment]
I think this is F-Droid's problem, I have had no issues generating apks. Maybe try to rebuild it again and see if it works.

**Comment by linsui** [comment]
I can reproduce it. https://gitlab.com/linsui/fdroiddata/-/jobs/2731412107 Sometimes F-Droid encounters lint issues. It seems those issues are ignored in AS.

**Comment by therealbluepandabear** [comment]
> I can reproduce it. https://gitlab.com/linsui/fdroiddata/-/jobs/2731412107 Sometimes F-Droid encounters lint issues. It seems those issues are ignored in AS.

That Lint error is meaningless, could you tell F-Droid to ignore it? Thanks.

**Comment by linsui** [comment]
I guess we can ignore it by adding some lintOptions. Not sure if that will fix the build.

> If that's not possible I will fix it, but you need to tell me how this will work -- as I will need to update the app, so does that mean that the version with the error will be 'skipped', I am confused?

I'll update the commit to build from the fixed one.

**Comment by therealbluepandabear** [comment]
> I guess we can ignore it by adding some lintOptions. Not sure if that will fix the build.
> 
> > If that's not possible I will fix it, but you need to tell me how this will work -- as I will need to update the app, so does that mean that the version with the error will be 'skipped', I am confused?
> 
> I'll update the commit to build from the fixed one.

Ah, if that's the case, I'll fix it in a day or two and I'll notify you. Cheers.

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
I cloned the repo and built it in AS. Then I got the same error. So maybe you need to start from a clean repo. The file may be cached.
![image](https://user-images.githubusercontent.com/36977733/179659213-68b092c8-9ed2-42fc-84d0-e8e254ec4bc5.png)

**Comment by linsui** [comment]
I tried to fix it. Though it builds, no scheme is generated...

**Comment by linsui** [comment]
> Furthermore, for some reason F-Droid is including images that I have also deleted from the 'phoneScreenshots' folder?

This is a very old issue but no one is working on it.

> The app has updated the description (and some images) values but is still stuck on 0.1.6 on F-Droid, take a look at this error please and why it's not updating.

I failed to build it. Are you able to build it from a fresh clone?

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
> Ok I've fixed it, but the files are unversioned in the 'schemas' folder, what do I do now?

How do you fix it?

**Comment by linsui** [comment]
What does unversioned mean? Maybe just add those files into this repo?

**Comment by linsui** [comment]
Let me have a try, thanks!

**Comment by linsui** [comment]
It works, thanks! I'll push the update.
