### ISSUE TITLE
[B] Pixels become slightly rectangular in portrait mode on rectangular canvases, causing the grid to not function properly 

### ISSUE THREAD

**Issue by therealbluepandabear** [therealbluepandabear/PixaPencil#252]
In portrait mode (on a rectangular canvas), the pixels become slightly rectangular which causes the grid not to function properly. Without a grid, it is hardly noticeable.

**Comment by Noitarud** [comment]
Replicated on lenovo android 10 tablet: portrait orientation with portrait canvas 200x100 the checkerboard (blank) is warped, same with either portrait/landscape canvas on landscape. Presume present in other mode but not as discernable.

You may have to limit to whole multipliers of canvas magnification (3x,4x), though I presume you wanted to have anti aliasing….

**Comment by therealbluepandabear** [comment]
> Replicated on lenovo android 10 tablet: portrait orientation with portrait canvas 200x100 the checkerboard (blank) is warped, same with either portrait/landscape canvas on landscape. Presume present in other mode but not as discernable.
> 
> You may have to limit to whole multipliers of canvas magnification (3x,4x), though I presume you wanted to have anti aliasing….

It has nothing to do with canvas magnification, and I am also unsure how that is related to anti aliasing. 

I believe that I have already fixed this issue or am close to fixing the issue, I just need to implement this into the `master` branch so this can be closed.

**Comment by Noitarud** [comment]
Ok, never mind. As for AA, I meant it could have blurring, when a detail is mostly toward one pixel it can adjust the shading so one gets more than the other, rather than having it in one pixel or the other, which would make a rippling effect (However that doesn't explain the grid issue being as bad as it is).

**Comment by therealbluepandabear** [comment]
I believe that this is fixed, or the issue is negligible.

**Comment by JeffRockatansky** [comment]
I am still experiencing this bug.

**Comment by therealbluepandabear** [comment]
> I am still experiencing this bug.
> 
> Version 0.1.8 from F-Droid.

Yeah, unfortunately the whole canvas sizing code needs a rewrite. New issue is here https://github.com/therealbluepandabear/PixaPencil/issues/272.
