### ISSUE TITLE
Remove TIF, BMP, and WEBP file formats

### ISSUE THREAD

**Issue by therealbluepandabear** [therealbluepandabear/PixaPencil#270]
TIF, BMP, and WEBP file formats are just adding un-needed bloat to the codebase. They're not file formats that would actually be used in real life.

**Comment by JoeEnderman** [comment]
I don't know about tif and webp. But bmp could actually have some use cases. Though, people could probably just convert from png if they need it.

**Comment by therealbluepandabear** [comment]
> I don't know about tif and webp. But bmp could actually have some use cases. Though, people could probably just convert from png if they need it.

How is BMP more useful than PNG or JPG, just curious?

**Comment by JoeEnderman** [comment]
It's not, but there are still some use cases. Just off the top of my head the marlin 3D printing slicer uses bmp to create a loading screen. In theory one could make a custom pixel screen for their 3D printer. I don't know why you couldn't convert a png into a bmp though. So my argument isn't exactly the strongest.

**Comment by therealbluepandabear** [comment]
If Android supported BMP natively I would probably keep it but since I need to use another library I think it's best to remove it. 

Thanks for your input though 😀

**Comment by JoeEnderman** [comment]
Thank you for listening.
