### ISSUE TITLE
[Improvement] Change icons for darken/lighten tool

### ISSUE THREAD

**Issue by therealbluepandabear** [therealbluepandabear/PixaPencil#43]
#### Improvement description
Change the current icon of the darken/lighten tool to something more clear.

#### Why is this improvement important to add?
Because some users are getting confused by the icons as to what the tools do.

**Comment by muslimsidiq** [comment]
I fix this by set android:hardwareAccelerated="false" on Manifest file CanvasActivity

**Comment by therealbluepandabear** [comment]
Great, I'll work on an official solution.

Would you be able to move this comment to [here](https://github.com/therealbluepandabear/PixaPencil/issues/60) to avoid confusion.

Cheers,
thebluepandabear
