### ISSUE TITLE
APK availability

### ISSUE THREAD

**Issue by IzzySoft** [therealbluepandabear/PixaPencil#58]
**Is your feature request related to a problem? Please describe.**
Looking where the app can be found so users can install it :smiley: 

**Describe the solution you'd like**
`git tag` releases so they [show up here](https://github.com/therealbluepandabear/PyxlMoose/releases), then have the release `*.apk` attached to the release.

**Describe alternatives you've considered**
Directly bringing it to [F-Droid](https://f-droid.org/) – would require tags as well but not necessarily APK files attached to them.

**Additional context**
A nice FOSS app like this would be nice to find where Android FOSS apps are at home (F-Droid), but should at least be available outside walled gardens (haven't checked whether your app is listed in any of the latter, though). So looking forward to have it available. Thanks in advance!

**Comment by therealbluepandabear** [comment]
Hi,

I am planning on releasing the `.apk` file in the releases section as you mentioned, and I'm also planning on putting the app on the F-Droid repo (as well as the Google Play Store to appeal to a larger audience).

However I only want to do so when the app is completely stable and relatively bug-free. I have observed a couple of bugs which I am working on fixing; when these are fixed I plan on releasing the app. 

I added landscape support to the app, but while testing it on a Galaxy A10 I noticed that - contrary to the emulator - the pixel grid data gets cleared when the user rotates their screen. This shouldn't be happening, and perhaps when I fix this bug I will consider releasing it 😃

I plan on releasing this app in the next month or so.

Thanks for posting the issue! If you have any questions you can reply and I will do my best to answer them.

**Comment by IzzySoft** [comment]
Thanks a lot! Should you need help with the F-Droid listing, I might assist. If you want a test-drive before that, with the APKs on the releases I might offer such via [my repo](https://apt.izzysoft.de/fdroid). Looking forward to the first one!

**Comment by therealbluepandabear** [comment]
Great, would it be possible to release it on both stores? If so, are there any things I need consider?

**Comment by IzzySoft** [comment]
It's always possible when conditions are met – the other question is if it's needed. If you mean F-Droid and my repo, a double-listing only makes sense if you either have a fast-paced release cycle (and thus need faster listings: F-Droid usually needs a few days to pick up as it needs to pass the build cycle there, while my repo picks up the ready-to-run APKs from your releases). If you mean F-Droid vs. Play, I guess that's a quite frequent combination (whether "F-Droid main" or my repo).

If you don't plan for GMS (or other proprietary components), you should be fine for all 3 places. In this case you shouldn't include them with your app at all. For other things, maybe the [collection of my notes](https://gitlab.com/-/snippets/1896503) gives you some ideas/help.

**Comment by therealbluepandabear** [comment]
Thanks for the info!

**Comment by therealbluepandabear** [comment]
I will be submitting a pull request soon to F-Droid.

**Comment by IzzySoft** [comment]
@therealbluepandabear if you need help, just "yell" :smile: F-Droid will ask for:

* fastlane metadata (see my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for help on that)
* tagged releases

(best processed in this order, so fastlane is covered by the tag)

**Comment by therealbluepandabear** [comment]
I have released `v0.0.1-beta1` on GitHub so I consider this issue partially closed, although it is non-production ready and contains bugs.

Once I release `v0.0.1` I will release it on F-Droid.

I will now close this specific issue and migrate the F-Droid problem to #79.
