### ISSUE TITLE
[Bug] Blur canvas on Android Oreo or API 27

### ISSUE THREAD

**Issue by muslimsidiq** [therealbluepandabear/PixaPencil#60]
**Describe the bug**
When run on android 8 (oreo sdk 27) canvas showing blurry, and when draw color to canvas its also blurred

**To Reproduce**
1. Open PyxlMoose.
2. Create new project or Edit Existing Project
3. Canvas showing blur, draw color also blur

**Expected behavior**
Canvas not blur, but show sharp pixel

**Screenshots**
![image](https://user-images.githubusercontent.com/5630555/160735522-fc36896d-7ea4-4477-890f-0786984a573d.png)

**Smartphone (please complete the following information):**
 - Emulator Android Studio
 - Android version 8, oreo SDK 27

**Comment by therealbluepandabear** [comment]
Hey,

Thanks for posting this issue request, I didn't know about this.

I'll try and fix it as soon as possible.

Cheers,
thebluepandabear

**Comment by therealbluepandabear** [comment]
Sorry, tried to for some time to fix this but to no avail. I will be restricting the app to Android 9.0+ as it seems to be working fine on 9.0. I might try and add better backwards compatibility in the future, but given that this is not really a serious app, I will be putting it on hold. Thanks for the issue request though!

**Comment by therealbluepandabear** [comment]
@muslimsidiq, forcing OpenGL Skia rendering in the 'Developer Settings' of your phone fixed the issue for me. I'll work on a better solution in the following days/weeks, hopefully this can be fixed. We'll see.

**Comment by muslimsidiq** [comment]
I fix this by set android:hardwareAccelerated="false" on Manifest file CanvasActivity

**Comment by therealbluepandabear** [comment]
That's great to hear!

I don't want to cause an argument, but that's a really bad solution as it slows down the app _significantly_. 

Here, I'll give you a tip as to how you can fix this and get great performance, trust me on this one.

Go to the 'Settings' section of your phone:

![image](https://user-images.githubusercontent.com/50536495/165015488-ae659001-8618-4ef3-8095-46fa33b3f683.png)

Now, tap on 'System':

![image](https://user-images.githubusercontent.com/50536495/165015520-810c5daa-b2d7-4ae8-9b71-d629e4053977.png)

Then, tap 'About Emulated Device':

![image](https://user-images.githubusercontent.com/50536495/165015590-1a3bbdef-6972-43e3-949d-85f44de84828.png)

Then, tap on 'Build Number' until you get the following:

![image](https://user-images.githubusercontent.com/50536495/165015629-e830f03d-f8c1-4327-b1b9-f8b623f0a7a4.png)

Now, go back:

![image](https://user-images.githubusercontent.com/50536495/165015658-d243773a-2de8-484c-9678-48eefb268add.png)

Then, you'll see the 'Developer Options' setting:

![image](https://user-images.githubusercontent.com/50536495/165015708-02238b11-b039-4582-b439-c0f6366fd285.png)

Tap on it, and navigate down until you find the following option:

![image](https://user-images.githubusercontent.com/50536495/165015766-13a470ba-a678-45e1-a718-470f35b509c8.png)

Tap on the option, and select 'Open GL (Skia)':

![image](https://user-images.githubusercontent.com/50536495/165015828-7ed07483-27a8-4165-8f09-7ddc62598684.png)

![image](https://user-images.githubusercontent.com/50536495/165015849-0603a28d-5d6d-4965-bc3e-ed39e58e8959.png)

Then, go back, and **close and reopen PixaPencil:**

![image](https://user-images.githubusercontent.com/50536495/165015917-1f7aacd3-94f0-4829-a244-2268e89464a2.png)

Then, when you reopen the app it should work fine:

![image](https://user-images.githubusercontent.com/50536495/165015966-91f4b13f-bdf7-42ff-927f-cf648d4cf29d.png)

Hopefully this helps, I also want this to be a reference guide for other users who are experiencing this problem.
Cheers,
thebluepandabear

**Comment by therealbluepandabear** [comment]
Hey,

I think I fixed it in the latest commit.

Could you update your porject and tell me if it works now OK?

Cheers,
thebluepandabear
