### ISSUE TITLE
[R] Release app on F-Droid

### ISSUE THREAD

**Issue by therealbluepandabear** [therealbluepandabear/PixaPencil#79]
Release the app on F-Droid (when the release is stable, so `v0.0.1`).

**Before adding app to F-Droid, fix the following:**

- [x] #100 
- [x] #97 
- [x] #74 
- [x] #101 
- [x] #102 
- [x] #103
- [x] #104

**Comment by IzzySoft** [comment]
Great, thanks for working on this! To help you on the way, I've just opened a PR providing you with some metadata F-Droid will ask for. Further, I've just added your app to my repo (will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.therealbluepandabear.pixapencil) around 6pm UTC today with the next sync). My library scanner (which is also used at F-Droid) approves, which is a good start! Just a dedicated icon is totally missing and better is available once the app will be listed at F-Droid.

Meanwhile: :crossed_fingers: for good progress on this task (and the app in general, of course!

**Comment by therealbluepandabear** [comment]
> Great, thanks for working on this! To help you on the way, I've just opened a PR providing you with some metadata F-Droid will ask for. Further, I've just added your app to my repo (will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.therealbluepandabear.pixapencil) around 6pm UTC today with the next sync). My library scanner (which is also used at F-Droid) approves, which is a good start! Just a dedicated icon is totally missing and better is available once the app will be listed at F-Droid.
> 
> Meanwhile: 🤞 for good progress on this task (and the app in general, of course!

Hey, any idea why my app isn't updating on your repo?

**Comment by therealbluepandabear** [comment]
I want to add my app on F-Droid, do you have any tutorials as to how to do this? It looks quite complex.

**Comment by therealbluepandabear** [comment]
I did a merge request on F-Droid, but I doubt it's well-made, could you perhaps assist me a bit in getting the app to F-Droid? Seems complex.

Here's the link to the PR:

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11129

**Comment by IzzySoft** [comment]
I cannot fix that as your branch is protected. Please do NOT accept the suggested changes yet but rather unprotect your branch so ***I*** can push in the commits. That will then enable the pipelines.

For the future: better avoid opening merge requests from the `master` branch. Always use dedicated branches for merge requests to avoid such trouble :wink:

**Comment by therealbluepandabear** [comment]
> I cannot fix that as your branch is protected. Please do NOT accept the suggested changes yet but rather unprotect your branch so _**I**_ can push in the commits. That will then enable the pipelines.
> 
> For the future: better avoid opening merge requests from the `master` branch. Always use dedicated branches for merge requests to avoid such trouble 😉

Unprotected it 👍

**Comment by IzzySoft** [comment]
No, you should definitely NOT merge it or it gets stuck again. As I wrote above, one of our team must push it as your account is not verified by GitLab (a verified account pushing frees you from that limitation). Now it's completely stuck, as the message says:

> Merge blocked: the source branch must be rebased onto the target branch.

If I try to push the rebase button:

> The rebase pre-receive hook failed: The project you were looking for could not be found or you don't have permission to view it..

Looks like your branch cannot be found anymore at all. So sorry, now I cannot help you with that anymore. I suggest we simply close the MR and you start a new one – this time from a dedicated branch to avoid that mess.

> Any idea why the icon isn't showing here?

Yes. There was none when your app was set up with my repo – and you didn't tell me you've added one to fastlane. Plus the one in fastlane exceeds the maximum size (512x512). I've now set it up, also to be picked from your fastlane and resized – should show up with the next sync tomorrow.

**Comment by therealbluepandabear** [comment]
Ok I will make a new one when I'm done with school

**Comment by therealbluepandabear** [comment]
Done: https://gitlab.com/therealbluepandabear/fdroiddata/-/merge_requests/new?merge_request%5Bsource_project_id%5D=36714889&merge_request%5Bsource_branch%5D=com.therealbluepandabear.pixapencil&merge_request%5Btarget_project_id%5D=36528&merge_request%5Btarget_branch%5D=master

**Comment by IzzySoft** [comment]
That worked out fine, thanks! See: one of the team pushed the changes this time, which unlocked the pipelines. That's our work-around for accounts which are not (yet) verified. As issuebot results look very good, I've just marked the merge request for review – so hopefully someone finds time soon to process it.

**Comment by IzzySoft** [comment]
Congrats! :tada:

Your app will appear on F-Droid in a few days now. About 10 days later I'd usually remove it from my repo, unless there's an explicit request to keep it. You can [check here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) for some pros and cons about it. If you want me to keep your app in my repo, just say so – otherwise I'll follow the "default path".

**Comment by therealbluepandabear** [comment]
Past 4 days, still waiting...

**Comment by IzzySoft** [comment]
Thanks! This will also save you from a bunch of similar issues opened over and again :see_no_evil:

**Comment by therealbluepandabear** [comment]
Great, app is on  F-Droid, any idea why the logo isn't showing here?

![image](https://user-images.githubusercontent.com/50536495/173155681-c2e54c98-a0d5-4178-bd39-5dbbe5b832d9.png)

**Comment by IzzySoft** [comment]
Now you can close this issue – welcome at F-Droid!

And as pointed out above: should you not state otherwise, I'll then remove the app from my repo in about a week.

Thanks for all your efforts, and for making PixaPencil available at F-Droid :heart_eyes:
